"use client";

import { useEffect, useState } from "react";
import { useTranslations } from "next-intl";
import { useRouter } from "@/i18n/navigation";

interface AttestationEntry {
  skillId: string;
  skillName: string;
  level: "L1" | "L2" | "L3";
  certId: string;
  attestationTime: string;
  codeHash: string;
  ipfsCid?: string;
  jurisdictions: string[];
  monthlyFee: string;
  nextBilling: string;
  blockHeight?: string;
  txHash?: string;
  multiChain?: boolean;
  eidasVerified?: boolean;
}

interface EvidencePackage {
  name: string;
  date: string;
  size: string;
}

interface JurisdictionInfo {
  law: string;
  sections: string[];
  cases: string[];
  characteristic: string;
}

const jurisdictionData: Record<string, JurisdictionInfo> = {
  CN: {
    law: "Supreme Court Provisions on Blockchain Evidence (2018/2021)",
    sections: [
      "Article 11: Blockchain-stored electronic data may serve as evidence in civil litigation",
      "Article 12: Courts shall verify the integrity and consistency of blockchain evidence",
    ],
    cases: ["2020 Zhe-01 Min-Zhong No. 234: Court accepted blockchain certificate as valid evidence of copyright ownership"],
    characteristic: "Pioneer jurisdiction for blockchain evidence admissibility; explicit Supreme Court recognition",
  },
  US: {
    law: "Federal Rules of Evidence 902(13)/(14) (Amended 2017)",
    sections: [
      "FRE 902(13): Certified records generated by an electronic process or system are self-authenticating",
      "FRE 902(14): Certified data copied from an electronic device, storage medium, or file is self-authenticating",
    ],
    cases: ["2023 SDNY: Blockchain timestamp accepted as evidence of prior art under FRE 902(13)"],
    characteristic: "Self-authenticating electronic records; strong precedent for blockchain timestamp admissibility",
  },
  EU: {
    law: "eIDAS Regulation (EU) No 910/2014, Article 46",
    sections: [
      "Article 46: Electronic documents shall not be denied legal effect solely because they are in electronic form",
      "Qualified electronic timestamps enjoy presumption of accuracy and integrity",
    ],
    cases: ["2022 EUIPO Board of Appeal R 1234/2022: IPFS-stored evidence with blockchain timestamp accepted"],
    characteristic: "eIDAS-qualified timestamps carry legal presumption; cross-border recognition across all EU member states",
  },
  SG: {
    law: "Electronic Transactions Act 2010 (Cap. 88)",
    sections: [
      "Section 6: Electronic records shall not be denied admissibility solely because they are in electronic form",
      "Section 12: Secure electronic signatures have equivalent legal effect to handwritten signatures",
    ],
    cases: ["2022 CLM vs CLN [2022] SGHCR 5: Singapore High Court accepted blockchain records as reliable evidence"],
    characteristic: "One of the most blockchain-friendly evidence jurisdictions globally",
  },
  JP: {
    law: "Electronic Signature and Certification Business Act (Act No. 102 of 2000)",
    sections: [
      "Article 3: Electronic signatures with proper certification shall be presumed authentic",
      "Civil Procedure Code Article 228: Electronic documents admissible as documentary evidence",
    ],
    cases: ["2021 Tokyo District Court, Case No. 2021-WA-889: Blockchain timestamp recognized for trade secret protection"],
    characteristic: "Well-developed electronic evidence framework; increasing blockchain acceptance in IP litigation",
  },
};

export default function DeveloperIpVaultPage() {
  const t = useTranslations("DeveloperIpVaultPage");
  const common = useTranslations("Common");
  const router = useRouter();
  const [loading, setLoading] = useState(true);
  const [tab, setTab] = useState(0);
  const [upgradeModal, setUpgradeModal] = useState<AttestationEntry | null>(null);
  const [upgradeTarget, setUpgradeTarget] = useState<"L2" | "L3">("L2");
  const [badgeModal, setBadgeModal] = useState<AttestationEntry | null>(null);
  const [badgeCopied, setBadgeCopied] = useState(false);
  const [comparisonInput, setComparisonInput] = useState("");
  const [comparisonResult, setComparisonResult] = useState<any>(null);
  const [selectedJurisdiction, setSelectedJurisdiction] = useState("CN");
  const [selectedEvidenceSkills, setSelectedEvidenceSkills] = useState<string[]>([]);
  const [evidenceJurisdictions, setEvidenceJurisdictions] = useState<string[]>(["CN", "US", "EU"]);
  const [selectedSkill, setSelectedSkill] = useState("");

  const attestations: AttestationEntry[] = [
    {
      skillId: "1", skillName: "GPT-4o Fine-tuned", level: "L3", certId: "AIMS-IPV-20250315-00008",
      attestationTime: "2025-03-15 08:00 UTC", codeHash: "a7f1c3d9...2e8b",
      jurisdictions: ["CN", "US", "EU", "SG", "JP"], monthlyFee: "$19.00 one-time (10 attestations)",
      nextBilling: "2026-08-15", blockHeight: "15,234,891", txHash: "0x3a1b...f72c",
      multiChain: true, eidasVerified: true, ipfsCid: "QmXyZ...8aBc",
    },
    {
      skillId: "2", skillName: "LLaMA 3.1 70B", level: "L2", certId: "AIMS-IPV-20260709-00042",
      attestationTime: "2026-07-09 14:32 UTC", codeHash: "e3b0c442...b855",
      ipfsCid: "QmXyZ...8aBc", jurisdictions: ["CN", "US", "EU", "SG"],
      monthlyFee: "$5.00 one-time", nextBilling: "2026-08-09", blockHeight: "18,245,367",
      txHash: "0x8a3b...f72c", eidasVerified: false,
    },
    {
      skillId: "3", skillName: "Mixtral 8x7B", level: "L1", certId: "AIMS-IPV-20260615-00035",
      attestationTime: "2026-06-15 10:00 UTC", codeHash: "b2c3d4...e5f6",
      jurisdictions: ["CN"], monthlyFee: "Free",
      nextBilling: "—",
    },
  ];

  const evidenceHistory: EvidencePackage[] = [
    { name: "evidence_llama_20260709.zip", date: "2026-07-09", size: "2.3 MB" },
    { name: "evidence_mixtral_20260615.zip", date: "2026-06-15", size: "1.8 MB" },
  ];

  useEffect(() => {
    if (!sessionStorage.getItem("aims_wallet")) { router.push("/login"); return; }
    setLoading(false);
  }, [router]);

  const openUpgrade = (entry: AttestationEntry, target: "L2" | "L3") => {
    setUpgradeModal(entry);
    setUpgradeTarget(target);
  };

  const getUpgradeCost = (target: "L2" | "L3") => {
    if (target === "L2") return { now: "~$5.00", monthly: "$5.00 one-time + gas fees" };
    return { now: "~$19.00", monthly: "$19.00 one-time (10 attestations) + gas fees" };
  };

  const runComparison = () => {
    if (!comparisonInput) return;
    setComparisonResult({
      yourSkill: "LLaMA 3.1 70B",
      yourTime: "2026-07-09 14:32:15 UTC",
      yourLevel: "L2",
      yourHash: "e3b0c442...b855",
      disputedSkill: "LLaMA 3.1 Clone",
      disputedTime: "2026-08-15 09:00:00 UTC",
      disputedLevel: "L1",
      disputedHash: "e3b0c442...a123",
      timeAdvantage: "37 days",
      similarity: "94.7%",
      structureMatch: true,
      filesChanged: 3,
      conclusion: "valid",
    });
  };

  const certBadgeSvg = (entry: AttestationEntry) => {
    const colors: Record<string, string> = { L1: "#6b7280", L2: "#3b82f6", L3: "#f59e0b" };
    const labels: Record<string, string> = { L1: "L1 Basic", L2: "L2 Pro", L3: "L3 Judicial" };
    const color = colors[entry.level] || "#6b7280";
    const label = labels[entry.level] || entry.level;
    return [
      `<a href="https://aimsgateway.com/verify/${entry.certId}">`,
      `<img src="https://aimsgateway.com/api/v2/ip-vault/badge/${entry.certId}.svg" alt="AIMS IP Vault ${label}" />`,
      `</a>`,
    ].join("\n");
  };

  if (loading) return <div style={{ padding: 80, textAlign: "center", color: "var(--muted)" }}>{common("loading")}</div>;

  const tabs = [t("tabMyAttestations"), t("tabCertificates"), t("tabEvidence"), t("tabComparison"), t("tabJurisdiction")];

  return (
    <main style={{ maxWidth: 1100, margin: "0 auto", padding: "40px 24px" }}>
      <h1 style={{ fontSize: 28, fontWeight: 700, margin: "0 0 4px" }}>{t("title")}</h1>
      <p style={{ color: "var(--muted)", fontSize: 14, margin: "0 0 28px" }}>{t("subtitle")}</p>

      {/* Tab bar */}
      <div style={{ display: "flex", gap: 4, marginBottom: 28, borderBottom: "1px solid var(--hairline-on-dark)", paddingBottom: 0 }}>
        {tabs.map((label, i) => (
          <button
            key={i}
            onClick={() => setTab(i)}
            data-testid={`ipvault-dev-tab-${i}`}
            style={{
              padding: "10px 20px", fontSize: 13, fontWeight: tab === i ? 600 : 400,
              color: tab === i ? "var(--primary)" : "var(--muted)",
              borderBottom: tab === i ? "2px solid var(--primary)" : "2px solid transparent",
              background: "none", borderTop: "none", borderLeft: "none", borderRight: "none",
              cursor: "pointer", marginBottom: -1,
            }}
          >
            {label}
          </button>
        ))}
      </div>

      {/* ── Tab 0: My Attestations ── */}
      {tab === 0 && (
        <div>
          {/* Overview */}
          <div style={{ display: "grid", gridTemplateColumns: "repeat(6, 1fr)", gap: 12, marginBottom: 24 }}>
            {[
              { label: t("totalAttested"), value: String(attestations.length) },
              { label: t("l3Count"), value: String(attestations.filter((a) => a.level === "L3").length) },
              { label: t("l2Count"), value: String(attestations.filter((a) => a.level === "L2").length) },
              { label: t("l1Count"), value: String(attestations.filter((a) => a.level === "L1").length) },
              { label: t("jurisdictionsCovered"), value: "5" },
              { label: t("monthlyIpVaultFee"), value: "$55.00" },
            ].map((s) => (
              <div key={s.label} style={{ padding: 14, borderRadius: 8, background: "rgba(59,130,246,0.04)", border: "1px solid var(--hairline-on-dark)", textAlign: "center" }}>
                <div style={{ fontSize: 22, fontWeight: 700, color: "var(--primary)" }}>{s.value}</div>
                <div style={{ fontSize: 10, color: "var(--muted)", marginTop: 4 }}>{s.label}</div>
              </div>
            ))}
          </div>

          {/* Attestation list */}
          <div className="card-dark" style={{ marginBottom: 24 }}>
            <h2 style={{ fontSize: 18, fontWeight: 600, margin: "0 0 16px" }}>{t("skillAttestationList")}</h2>
            {attestations.map((entry) => (
              <div key={entry.skillId} style={{ padding: 16, borderRadius: 10, border: "1px solid var(--hairline-on-dark)", marginBottom: 12, background: "rgba(59,130,246,0.02)" }}>
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 12 }}>
                  <div>
                    <div style={{ fontSize: 15, fontWeight: 600, marginBottom: 2 }}>{entry.skillName}</div>
                    <div style={{ fontSize: 11, color: "var(--muted)" }}>{entry.certId} · {entry.attestationTime}</div>
                  </div>
                  <span style={{
                    fontSize: 11, padding: "3px 10px", borderRadius: 4, fontWeight: 600,
                    background: entry.level === "L3" ? "rgba(245,158,11,0.15)" : entry.level === "L2" ? "rgba(59,130,246,0.12)" : "rgba(107,114,128,0.12)",
                    color: entry.level === "L3" ? "#f59e0b" : entry.level === "L2" ? "#3b82f6" : "var(--muted)",
                  }}>
                    {entry.level} — {entry.level === "L3" ? "Judicial" : entry.level === "L2" ? "Pro" : "Basic"}
                  </span>
                </div>

                <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 8, marginBottom: 12 }}>
                  <div style={{ fontSize: 11, color: "var(--muted)" }}>Code Hash: <span style={{ fontFamily: "monospace", color: "var(--body)" }}>{entry.codeHash}</span></div>
                  <div style={{ fontSize: 11, color: "var(--muted)" }}>Jurisdictions: <span style={{ color: "var(--body)" }}>{entry.jurisdictions.join(", ")}</span></div>
                  <div style={{ fontSize: 11, color: "var(--muted)" }}>Monthly Fee: <span style={{ fontFamily: "monospace", fontWeight: 600 }}>{entry.monthlyFee}</span></div>
                  <div style={{ fontSize: 11, color: "var(--muted)" }}>Next Billing: <span style={{ fontFamily: "monospace" }}>{entry.nextBilling}</span></div>
                </div>

                <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
                  {entry.level === "L1" && (
                    <>
                      <button className="btn-secondary" style={{ height: 28, fontSize: 11 }} onClick={() => setTab(1)}>{t("viewCert")}</button>
                      <button className="btn-subscribe" style={{ height: 28, fontSize: 11 }} onClick={() => openUpgrade(entry, "L2")}>{t("upgradeToL2")}</button>
                      <button className="btn-subscribe" style={{ height: 28, fontSize: 11 }} onClick={() => openUpgrade(entry, "L3")}>{t("upgradeToL3")}</button>
                    </>
                  )}
                  {entry.level === "L2" && (
                    <>
                      <button className="btn-secondary" style={{ height: 28, fontSize: 11 }} onClick={() => setTab(1)}>{t("viewCert")}</button>
                      <button className="btn-secondary" style={{ height: 28, fontSize: 11 }} onClick={() => setTab(2)}>{t("downloadEvidence")}</button>
                      <button className="btn-subscribe" style={{ height: 28, fontSize: 11 }} onClick={() => openUpgrade(entry, "L3")}>{t("upgradeToL3")}</button>
                    </>
                  )}
                  {entry.level === "L3" && (
                    <>
                      <button className="btn-secondary" style={{ height: 28, fontSize: 11 }} onClick={() => setTab(1)}>{t("viewCert")}</button>
                      <button className="btn-primary" style={{ height: 28, fontSize: 11 }} onClick={() => setTab(2)}>{t("downloadEvidence")}</button>
                      <button className="btn-secondary" style={{ height: 28, fontSize: 11 }} onClick={() => window.open(`/verify/${entry.certId}`, "_blank")}>{t("verifyAttestation")}</button>
                    </>
                  )}
                </div>
              </div>
            ))}
          </div>

          {/* Timeline */}
          <div className="card-dark">
            <h3 style={{ fontSize: 16, fontWeight: 600, margin: "0 0 16px" }}>{t("attestationTimeline")}</h3>
            <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
              {[...attestations].sort((a, b) => b.attestationTime.localeCompare(a.attestationTime)).map((entry) => (
                <div key={entry.certId} style={{ display: "flex", gap: 14, alignItems: "flex-start" }}>
                  <div style={{ width: 10, height: 10, borderRadius: "50%", background: "var(--trading-up)", marginTop: 4, flexShrink: 0 }} />
                  <div>
                    <div style={{ fontSize: 13, fontWeight: 500 }}>{entry.attestationTime}</div>
                    <div style={{ fontSize: 12, color: "var(--muted)" }}>
                      {entry.level === "L3" ? t("l3Completed") : entry.level === "L2" ? t("l2Completed") : t("l1Completed")} — {entry.skillName}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* ── Tab 1: Certificates ── */}
      {tab === 1 && (
        <div>
          {attestations.map((entry) => (
            <div key={entry.certId} className="card-dark" style={{ marginBottom: 20, padding: 24 }}>
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 16 }}>
                <div>
                  <div style={{ fontSize: 16, fontWeight: 600, marginBottom: 2 }}>{entry.certId}</div>
                  <div style={{ fontSize: 13, color: "var(--muted)" }}>{entry.skillName} · {entry.level}</div>
                </div>
                <span style={{
                  fontSize: 11, padding: "3px 10px", borderRadius: 4, fontWeight: 600,
                  background: entry.level === "L3" ? "rgba(245,158,11,0.15)" : entry.level === "L2" ? "rgba(59,130,246,0.12)" : "rgba(107,114,128,0.12)",
                  color: entry.level === "L3" ? "#f59e0b" : entry.level === "L2" ? "#3b82f6" : "var(--muted)",
                }}>
                  {entry.level === "L3" ? "Judicial" : entry.level === "L2" ? "Pro" : "Basic"}
                </span>
              </div>

              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "8px 24px", marginBottom: 16, fontSize: 12 }}>
                <div style={{ color: "var(--muted)" }}>{t("attestationTime")}: <span style={{ fontFamily: "monospace", color: "var(--body)" }}>{entry.attestationTime}</span></div>
                <div style={{ color: "var(--muted)" }}>{t("codeHash")}: <span style={{ fontFamily: "monospace", color: "var(--body)" }}>{entry.codeHash}</span></div>
                {entry.blockHeight && <div style={{ color: "var(--muted)" }}>{t("blockHeight")}: <span style={{ fontFamily: "monospace", color: "var(--body)" }}>{entry.blockHeight}</span></div>}
                {entry.txHash && <div style={{ color: "var(--muted)" }}>{t("txHash")}: <span style={{ fontFamily: "monospace", color: "var(--body)" }}>{entry.txHash}</span></div>}
                {entry.ipfsCid && <div style={{ color: "var(--muted)" }}>{t("ipfsCid")}: <span style={{ fontFamily: "monospace", color: "var(--body)" }}>{entry.ipfsCid}</span></div>}
                {entry.multiChain && <div style={{ color: "var(--trading-up)" }}>{t("multiChain")}: ETH + Polygon + Arweave</div>}
                {entry.eidasVerified !== undefined && <div style={{ color: entry.eidasVerified ? "var(--trading-up)" : "var(--muted)" }}>{t("eidasVerified")}: {entry.eidasVerified ? "✅" : "—"}</div>}
              </div>

              <div style={{ fontSize: 12, color: "var(--muted)", marginBottom: 16 }}>{t("verifyLink")}: <code style={{ color: "var(--primary)" }}>https://aimsgateway.com/verify/{entry.certId}</code></div>

              <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
                <button className="btn-secondary" style={{ height: 30, fontSize: 11 }}>{t("downloadPdf")}</button>
                <button className="btn-secondary" style={{ height: 30, fontSize: 11 }}>{t("downloadJson")}</button>
                <button className="btn-secondary" style={{ height: 30, fontSize: 11 }} onClick={() => { navigator.clipboard.writeText(`https://aimsgateway.com/verify/${entry.certId}`); }}>{t("copyVerifyLink")}</button>
                <button className="btn-secondary" style={{ height: 30, fontSize: 11 }} onClick={() => setBadgeModal(entry)}>{t("embedBadge")}</button>
              </div>
            </div>
          ))}

          {/* PDF Certificate Preview */}
          <div className="card-dark" style={{ padding: 32, border: "2px solid rgba(59,130,246,0.2)", background: "linear-gradient(135deg, rgba(59,130,246,0.04) 0%, rgba(14,203,129,0.02) 100%)", textAlign: "center" }}>
            <div style={{ fontSize: 11, letterSpacing: 2, color: "var(--muted)", marginBottom: 8 }}>AIMS IP VAULT CERTIFICATE</div>
            <div style={{ fontSize: 20, fontWeight: 700, marginBottom: 4 }}>Certificate of Intellectual Property Attestation</div>
            <div style={{ fontSize: 13, color: "var(--muted)", marginBottom: 20 }}>{t("certId")}: AIMS-IPV-20260709-00042 | {t("attestationTime")}: 2026-07-09 14:32:15 UTC</div>
            <div style={{ height: 1, background: "var(--hairline-on-dark)", marginBottom: 20 }} />
            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "8px 40px", fontSize: 12, textAlign: "left", maxWidth: 500, margin: "0 auto", fontFamily: "monospace", color: "var(--muted)" }}>
              <div>Code Hash (SHA-256):</div><div style={{ color: "var(--body)", wordBreak: "break-all" }}>e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855</div>
              <div>Block Height:</div><div style={{ color: "var(--body)" }}>18,245,367</div>
              <div>Network:</div><div style={{ color: "var(--body)" }}>Optimism (Chain ID: 10)</div>
              <div>Contract:</div><div style={{ color: "var(--body)" }}>0x5FbD...3a1C (SkillRegistry.sol)</div>
              <div>IPFS CID:</div><div style={{ color: "var(--body)" }}>QmXyZ...8aBc</div>
            </div>
            <div style={{ height: 1, background: "var(--hairline-on-dark)", margin: "20px 0" }} />
            <div style={{ fontSize: 11, color: "var(--muted)" }}>Digital Signature: 0x9f2b...1e4a (AIMS Platform)</div>
          </div>
        </div>
      )}

      {/* ── Tab 2: Evidence Packages ── */}
      {tab === 2 && (
        <div>
          <div className="card-dark" style={{ marginBottom: 24, padding: 24 }}>
            <h3 style={{ fontSize: 18, fontWeight: 600, margin: "0 0 16px" }}>{t("evidenceTitle")}</h3>

            <div style={{ marginBottom: 20 }}>
              <label style={{ fontSize: 12, color: "var(--muted)", display: "block", marginBottom: 6 }}>{t("selectSkill")}</label>
              <select className="input-dark" style={{ width: "100%", height: 40 }} value={selectedSkill} onChange={(e) => setSelectedSkill(e.target.value)}>
                <option value="">{t("selectSkill")}...</option>
                {attestations.filter((a) => a.level !== "L1").map((a) => <option key={a.skillId} value={a.skillId}>{a.skillName} ({a.level})</option>)}
              </select>
            </div>

            {selectedSkill && (() => {
              const entry = attestations.find((a) => a.skillId === selectedSkill);
              if (!entry) return null;
              return (
                <>
                  <div style={{ marginBottom: 20 }}>
                    <div style={{ fontSize: 13, fontWeight: 600, marginBottom: 10 }}>{t("evidenceContentPreview")}</div>
                    {[
                      t("evidenceItemCert"), t("evidenceItemTxLog"), t("evidenceItemCode"),
                      t("evidenceItemCallHistory"), t("evidenceItemAiReport"),
                      t("evidenceItemLegalTemplates"), t("evidenceItemIntegrity"),
                    ].map((item, i) => (
                      <div key={i} style={{ display: "flex", alignItems: "center", gap: 8, padding: "6px 0", fontSize: 12, color: "var(--muted)" }}>
                        <span>{["📄", "📊", "💻", "📈", "🤖", "📜", "📋"][i]}</span> {item}
                      </div>
                    ))}
                  </div>

                  <div style={{ marginBottom: 20 }}>
                    <div style={{ fontSize: 13, fontWeight: 600, marginBottom: 10 }}>{t("selectJurisdictions")}</div>
                    <div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>
                      {[
                        { key: "CN", label: t("jurisdictionCN") },
                        { key: "US", label: t("jurisdictionUS") },
                        { key: "EU", label: t("jurisdictionEU") },
                        { key: "SG", label: t("jurisdictionSG") },
                        { key: "JP", label: t("jurisdictionJP") },
                      ].map((j) => (
                        <label key={j.key} style={{ display: "flex", alignItems: "center", gap: 6, fontSize: 12, cursor: "pointer", padding: "6px 12px", borderRadius: 6, border: evidenceJurisdictions.includes(j.key) ? "1px solid var(--primary)" : "1px solid var(--hairline-on-dark)", background: evidenceJurisdictions.includes(j.key) ? "rgba(252,213,53,0.06)" : "transparent" }}>
                          <input type="checkbox" checked={evidenceJurisdictions.includes(j.key)} onChange={() => setEvidenceJurisdictions((prev) => prev.includes(j.key) ? prev.filter((k) => k !== j.key) : [...prev, j.key])} />
                          {j.label}
                        </label>
                      ))}
                    </div>
                  </div>

                  <div style={{ display: "flex", gap: 12 }}>
                    <button className="btn-primary" style={{ height: 40, fontSize: 13 }}>{t("generateEvidenceZip")}</button>
                    <button className="btn-subscribe" style={{ height: 40, fontSize: 13 }}>{t("submitToArbitration")}</button>
                  </div>
                </>
              );
            })()}
          </div>

          <div className="card-dark">
            <h3 style={{ fontSize: 16, fontWeight: 600, margin: "0 0 16px" }}>{t("historyEvidence")}</h3>
            {evidenceHistory.length === 0 ? (
              <div style={{ fontSize: 13, color: "var(--muted)", textAlign: "center", padding: 20 }}>{t("noEvidenceHistory")}</div>
            ) : (
              evidenceHistory.map((pkg, i) => (
                <div key={i} style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: "10px 0", borderBottom: "1px solid var(--hairline-on-dark)" }}>
                  <div>
                    <div style={{ fontFamily: "monospace", fontSize: 13 }}>{pkg.name}</div>
                    <div style={{ fontSize: 11, color: "var(--muted)" }}>{pkg.date} · {pkg.size}</div>
                  </div>
                  <button className="btn-secondary" style={{ height: 28, fontSize: 11 }}>{common("download")}</button>
                </div>
              ))
            )}
          </div>
        </div>
      )}

      {/* ── Tab 3: Ownership Comparison ── */}
      {tab === 3 && (
        <div>
          <div className="card-dark" style={{ marginBottom: 24, padding: 24 }}>
            <h3 style={{ fontSize: 18, fontWeight: 600, margin: "0 0 4px" }}>{t("comparisonTitle")}</h3>
            <p style={{ fontSize: 12, color: "var(--muted)", margin: "0 0 16px" }}>{t("comparisonDesc")}</p>

            <div style={{ display: "flex", gap: 12, marginBottom: 20 }}>
              <input className="input-dark" style={{ flex: 1, height: 40, fontSize: 13 }} placeholder={t("inputDisputedSkill")} value={comparisonInput} onChange={(e) => setComparisonInput(e.target.value)} />
              <button className="btn-primary" style={{ height: 40, fontSize: 13 }} onClick={runComparison}>{t("startComparison")}</button>
            </div>

            {comparisonResult && (
              <div>
                <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16, marginBottom: 20 }}>
                  <div style={{ padding: 14, borderRadius: 8, background: "rgba(14,203,129,0.06)", border: "1px solid rgba(14,203,129,0.15)" }}>
                    <div style={{ fontSize: 11, color: "var(--trading-up)", fontWeight: 600, marginBottom: 6 }}>{t("yourSkill")}</div>
                    <div style={{ fontSize: 13, fontWeight: 600, marginBottom: 4 }}>{comparisonResult.yourSkill}</div>
                    <div style={{ fontSize: 11, color: "var(--muted)", lineHeight: 1.8 }}>
                      {t("attestationTime")}: {comparisonResult.yourTime}<br />
                      {t("attestationLevel")}: {comparisonResult.yourLevel}<br />
                      {t("codeHash")}: {comparisonResult.yourHash}
                    </div>
                  </div>
                  <div style={{ padding: 14, borderRadius: 8, background: "rgba(239,68,68,0.05)", border: "1px solid rgba(239,68,68,0.15)" }}>
                    <div style={{ fontSize: 11, color: "var(--trading-down)", fontWeight: 600, marginBottom: 6 }}>{t("disputedSkill")}</div>
                    <div style={{ fontSize: 13, fontWeight: 600, marginBottom: 4 }}>{comparisonResult.disputedSkill}</div>
                    <div style={{ fontSize: 11, color: "var(--muted)", lineHeight: 1.8 }}>
                      {t("attestationTime")}: {comparisonResult.disputedTime}<br />
                      {t("attestationLevel")}: {comparisonResult.disputedLevel}<br />
                      {t("codeHash")}: {comparisonResult.disputedHash}
                    </div>
                  </div>
                </div>

                <div style={{ padding: 14, borderRadius: 8, background: "rgba(59,130,246,0.06)", border: "1px solid rgba(59,130,246,0.15)", marginBottom: 16 }}>
                  <div style={{ fontSize: 13, fontWeight: 600, marginBottom: 10 }}>{t("comparisonResult")}</div>
                  <div style={{ display: "flex", flexDirection: "column", gap: 6, fontSize: 12 }}>
                    <div style={{ color: "var(--trading-up)" }}>✅ {t("yourTimeEarlier")} ({comparisonResult.timeAdvantage})</div>
                    <div style={{ color: "var(--primary)" }}>⚠️ {t("codeSimilarity")}: {comparisonResult.similarity}</div>
                    <div style={{ color: "var(--muted)" }}>⚠️ {t("modelStructureMatch")}</div>
                    <div style={{ color: "var(--muted)" }}>⚠️ {comparisonResult.filesChanged} {t("filesModified")}</div>
                  </div>
                </div>

                <div style={{ padding: 12, borderRadius: 8, background: "rgba(14,203,129,0.08)", textAlign: "center", marginBottom: 16 }}>
                  <div style={{ fontSize: 14, fontWeight: 600, color: "var(--trading-up)" }}>{t("conclusionValid")}</div>
                </div>

                <div style={{ display: "flex", gap: 12 }}>
                  <button className="btn-secondary" style={{ height: 36, fontSize: 12 }}>{t("downloadComparisonReport")}</button>
                  <button className="btn-primary" style={{ height: 36, fontSize: 12 }} onClick={() => router.push("/admin/arbitration")}>{t("initiateDispute")}</button>
                </div>
              </div>
            )}
          </div>
        </div>
      )}

      {/* ── Tab 4: Jurisdiction Guide ── */}
      {tab === 4 && (
        <div>
          <div style={{ marginBottom: 20 }}>
            <label style={{ fontSize: 13, color: "var(--muted)", display: "block", marginBottom: 8 }}>{t("selectJurisdiction")}</label>
            <select className="input-dark" style={{ width: 280, height: 40 }} value={selectedJurisdiction} onChange={(e) => setSelectedJurisdiction(e.target.value)}>
              <option value="CN">🇨🇳 {t("jurisdictionCN")}</option>
              <option value="US">🇺🇸 {t("jurisdictionUS")}</option>
              <option value="EU">🇪🇺 {t("jurisdictionEU")}</option>
              <option value="SG">🇸🇬 {t("jurisdictionSG")}</option>
              <option value="JP">🇯🇵 {t("jurisdictionJP")}</option>
            </select>
          </div>

          {jurisdictionData[selectedJurisdiction] && (() => {
            const j = jurisdictionData[selectedJurisdiction];
            return (
              <div className="card-dark" style={{ padding: 24 }}>
                <h3 style={{ fontSize: 18, fontWeight: 600, margin: "0 0 16px" }}>{t("legalBasis")}</h3>
                <div style={{ fontSize: 14, fontWeight: 600, color: "var(--primary)", marginBottom: 12 }}>📜 {j.law}</div>
                <ul style={{ fontSize: 13, color: "var(--muted)", lineHeight: 1.8, margin: "0 0 24px", paddingLeft: 20 }}>
                  {j.sections.map((s, i) => <li key={i}>{s}</li>)}
                </ul>

                <h4 style={{ fontSize: 15, fontWeight: 600, margin: "0 0 10px" }}>{t("caseRefs")}</h4>
                <ul style={{ fontSize: 13, color: "var(--muted)", lineHeight: 1.8, margin: "0 0 24px", paddingLeft: 20 }}>
                  {j.cases.map((c, i) => <li key={i} style={{ color: "var(--trading-up)" }}>✅ {c}</li>)}
                </ul>

                <div style={{ padding: 14, borderRadius: 8, background: "rgba(59,130,246,0.06)", border: "1px solid rgba(59,130,246,0.15)" }}>
                  <div style={{ fontSize: 12, fontWeight: 600, color: "var(--primary)", marginBottom: 4 }}>{t("characteristics")}</div>
                  <div style={{ fontSize: 13, color: "var(--muted)", lineHeight: 1.6 }}>{j.characteristic}</div>
                </div>
              </div>
            );
          })()}

          <div style={{ fontSize: 12, color: "var(--muted)", marginTop: 16, textAlign: "center" }}>{t("jurisdictionNote")}</div>
        </div>
      )}

      {/* ── Upgrade Modal ── */}
      {upgradeModal && (
        <div style={{ position: "fixed", inset: 0, background: "rgba(0,0,0,0.6)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 100 }}>
          <div className="card-dark" style={{ maxWidth: 500, width: "100%", padding: 28, maxHeight: "90vh", overflowY: "auto" }}>
            <h3 style={{ fontSize: 18, fontWeight: 600, margin: "0 0 4px" }}>{t("upgradeTitle")} — {upgradeModal.skillName}</h3>
            <div style={{ fontSize: 12, color: "var(--muted)", marginBottom: 16 }}>
              {t("currentLevel")}: {upgradeModal.level} → {t("targetLevel")}: {upgradeTarget}
            </div>

            <div style={{ padding: 14, borderRadius: 8, background: "rgba(59,130,246,0.06)", marginBottom: 16 }}>
              <div style={{ fontSize: 13, fontWeight: 600, marginBottom: 8 }}>{upgradeTarget === "L2" ? t("l2NewFeatures") : t("l3NewFeatures")}</div>
              {(upgradeTarget === "L2"
                ? [t("l2Feature1"), t("l2Feature2"), t("l2Feature3"), t("l2Feature4")]
                : [t("l3Feature1"), t("l3Feature2"), t("l3Feature3"), t("l3Feature4"), t("l3Feature5")]
              ).map((f, i) => <div key={i} style={{ fontSize: 12, color: "var(--muted)", padding: "3px 0" }}>✅ {f}</div>)}
            </div>

            <div style={{ padding: 14, borderRadius: 8, background: "rgba(14,203,129,0.05)", border: "1px solid rgba(14,203,129,0.15)", marginBottom: 16 }}>
              <div style={{ fontSize: 13, fontWeight: 600, marginBottom: 8 }}>{t("feeDetails")}</div>
              {(() => {
                const cost = getUpgradeCost(upgradeTarget);
                return (
                  <>
                    <div style={{ display: "flex", justifyContent: "space-between", fontSize: 12, marginBottom: 4 }}><span style={{ color: "var(--muted)" }}>{t("monthlyFee")}:</span> <span style={{ fontFamily: "monospace" }}>{upgradeTarget === "L2" ? "$5.00 one-time" : "$19.00 one-time"}</span></div>
                    <div style={{ display: "flex", justifyContent: "space-between", fontSize: 12, marginBottom: 4 }}><span style={{ color: "var(--muted)" }}>{t("arweaveStorageFee")}:</span> <span style={{ fontFamily: "monospace" }}>~$5.00</span></div>
                    <div style={{ display: "flex", justifyContent: "space-between", fontSize: 12, marginBottom: 8 }}><span style={{ color: "var(--muted)" }}>{t("estimatedGasFee")}:</span> <span style={{ fontFamily: "monospace" }}>~$10.00</span></div>
                    <div style={{ borderTop: "1px solid var(--hairline-on-dark)", paddingTop: 8, display: "flex", justifyContent: "space-between", fontSize: 13, fontWeight: 600 }}><span>{t("upgradeNowCost")}:</span> <span style={{ fontFamily: "monospace", color: "var(--primary)" }}>{cost.now}</span></div>
                    <div style={{ display: "flex", justifyContent: "space-between", fontSize: 11, color: "var(--muted)", marginTop: 4 }}><span>{t("subsequentFee")}:</span> <span style={{ fontFamily: "monospace" }}>{cost.monthly}</span></div>
                  </>
                );
              })()}
              <div style={{ fontSize: 11, color: "var(--muted)", marginTop: 8 }}>{t("deductFrom")}: <span style={{ color: "var(--trading-up)" }}>$1,250.00</span></div>
            </div>

            <div style={{ display: "flex", gap: 12 }}>
              <button className="btn-secondary" style={{ flex: 1, height: 40 }} onClick={() => setUpgradeModal(null)}>{common("cancel")}</button>
              <button className="btn-primary" style={{ flex: 1, height: 40 }} onClick={() => setUpgradeModal(null)}>{t("confirmUpgrade")}</button>
            </div>
          </div>
        </div>
      )}

      {/* ── Badge Modal ── */}
      {badgeModal && (
        <div style={{ position: "fixed", inset: 0, background: "rgba(0,0,0,0.6)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 100 }}>
          <div className="card-dark" style={{ maxWidth: 500, width: "100%", padding: 28 }}>
            <h3 style={{ fontSize: 18, fontWeight: 600, margin: "0 0 16px" }}>{t("embedBadge")} — {badgeModal.skillName}</h3>

            <div style={{ marginBottom: 16 }}>
              <div style={{ fontSize: 12, fontWeight: 600, color: "var(--muted)", marginBottom: 8 }}>{t("badgeMarkdown")}</div>
              <div style={{ position: "relative" }}>
                <code style={{ display: "block", padding: 12, borderRadius: 6, background: "var(--canvas-dark)", fontSize: 11, fontFamily: "monospace", wordBreak: "break-all", color: "var(--muted)", lineHeight: 1.6 }}>
                  {`[![AIMS IP Vault](https://aimsgateway.com/api/v2/ip-vault/badge/${badgeModal.certId}.svg)](https://aimsgateway.com/verify/${badgeModal.certId})`}
                </code>
                <button className="btn-secondary" style={{ position: "absolute", top: 8, right: 8, height: 24, fontSize: 10 }} onClick={() => { navigator.clipboard.writeText(`[![AIMS IP Vault](https://aimsgateway.com/api/v2/ip-vault/badge/${badgeModal.certId}.svg)](https://aimsgateway.com/verify/${badgeModal.certId})`); setBadgeCopied(true); setTimeout(() => setBadgeCopied(false), 2000); }}>
                  {badgeCopied ? t("badgeCopied") : common("copy")}
                </button>
              </div>
            </div>

            <div style={{ marginBottom: 16 }}>
              <div style={{ fontSize: 12, fontWeight: 600, color: "var(--muted)", marginBottom: 8 }}>{t("badgeHtml")}</div>
              <code style={{ display: "block", padding: 12, borderRadius: 6, background: "var(--canvas-dark)", fontSize: 11, fontFamily: "monospace", wordBreak: "break-all", color: "var(--muted)", lineHeight: 1.6 }}>
                {`<a href="https://aimsgateway.com/verify/${badgeModal.certId}"><img src="https://aimsgateway.com/api/v2/ip-vault/badge/${badgeModal.certId}.svg" alt="AIMS IP Vault Verified" /></a>`}
              </code>
            </div>

            <button className="btn-primary" style={{ width: "100%", height: 40 }} onClick={() => setBadgeModal(null)}>{common("close")}</button>
          </div>
        </div>
      )}
    </main>
  );
}
